@SocialMediaAppBackend_HostAddress = http://localhost:5226

POST {{SocialMediaAppBackend_HostAddress}}/posts/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdDQiLCJleHAiOjE3NzY3Nzk4MTUsImlzcyI6InNvY2lhbC1tZWRpYS1hcHAtYmFja2VuZCIsImF1ZCI6InNvY2lhbC1tZWRpYS1hcHAtZnJvbnRlbmQifQ.HRwl1b9ge7LwuJIWId8n8pY1Rc1MIkEjuqDb4kP_dhM

{
    "content": "testtestesttesesttesesttesesttesesttesesttesesttesesttesesttesesttesesttesesttesesttesesttes"
}
###

GET {{SocialMediaAppBackend_HostAddress}}/posts/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdDQiLCJleHAiOjE3NzY3NzI2MDMsImlzcyI6InNvY2lhbC1tZWRpYS1hcHAtYmFja2VuZCIsImF1ZCI6InNvY2lhbC1tZWRpYS1hcHAtZnJvbnRlbmQifQ.xKY6LCycX0QZAH29F250uLk4cMr7xN5hijl7wK8hJr0


###


DELETE {{SocialMediaAppBackend_HostAddress}}/posts/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImV4cCI6MTc3NjY5NjcwMSwiaXNzIjoic29jaWFsLW1lZGlhLWFwcC1iYWNrZW5kIiwiYXVkIjoic29jaWFsLW1lZGlhLWFwcC1mcm9udGVuZCJ9.w3JH68DGt6p9bKCAFJWtXy_4GadgAo_NUoUD85deA8k